
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AVAILABLE AVAILABLE_360 BOOLEAN COMA COMPETITION_ID COMPETITION_NAME COR_ABRE COR_CIERRA COUNTRY DOSPUNTOS GENDER INTERNATIONAL LLAVE_ABRE LLAVE_CIERRA MATCH NULL NUMBER ROOT SEASON_ID SEASON_NAME STRING TIMESTAMP UPDATED UPDATED_360 YOUTHjson : LLAVE_ABRE contenido LLAVE_CIERRAcontenido : ROOT DOSPUNTOS COR_ABRE elementos COR_CIERRAelementos : LLAVE_ABRE estructura LLAVE_CIERRA COMAelementos : LLAVE_ABRE estructura LLAVE_CIERRAestructura : competition_id season_id country competition_name gender youth international season_name matchcompetition_id : COMPETITION_ID DOSPUNTOS NUMBER COMAseason_id : SEASON_ID DOSPUNTOS NUMBER COMAcountry : COUNTRY DOSPUNTOS STRING COMAcompetition_name : COMPETITION_NAME DOSPUNTOS STRING COMAgender : GENDER DOSPUNTOS STRING COMAyouth : YOUTH DOSPUNTOS BOOLEAN COMAinternational : INTERNATIONAL DOSPUNTOS BOOLEAN COMAseason_name : SEASON_NAME DOSPUNTOS STRING COMAmatch : MATCH DOSPUNTOS LLAVE_ABRE estructura_match LLAVE_CIERRAestructura_match : updated updated360 available360 availableupdated : UPDATED DOSPUNTOS TIMESTAMP COMAupdated : UPDATED DOSPUNTOS NULL COMAupdated360 : UPDATED_360 DOSPUNTOS TIMESTAMP COMAupdated360 : UPDATED_360 DOSPUNTOS NULL COMAavailable360 : AVAILABLE_360 DOSPUNTOS TIMESTAMP COMAavailable360 : AVAILABLE_360 DOSPUNTOS NULL COMAavailable : AVAILABLE DOSPUNTOS TIMESTAMPavailable : AVAILABLE DOSPUNTOS NULL'
    
_lr_action_items = {'LLAVE_ABRE':([0,7,53,],[2,9,56,]),'$end':([1,5,],[0,-1,]),'ROOT':([2,],[4,]),'LLAVE_CIERRA':([3,10,11,48,58,61,70,82,83,],[5,-2,14,-5,61,-14,-15,-22,-23,]),'DOSPUNTOS':([4,13,16,20,24,29,34,39,44,49,60,63,66,71,],[6,17,21,25,30,35,40,45,50,53,64,67,72,77,]),'COR_ABRE':([6,],[7,]),'COR_CIERRA':([8,14,18,],[10,-4,-3,]),'COMPETITION_ID':([9,],[13,]),'SEASON_ID':([12,27,],[16,-6,]),'COMA':([14,22,26,31,36,41,46,51,54,68,69,73,74,78,79,],[18,27,32,37,42,47,52,55,57,75,76,80,81,84,85,]),'COUNTRY':([15,32,],[20,-7,]),'NUMBER':([17,21,],[22,26,]),'COMPETITION_NAME':([19,37,],[24,-8,]),'GENDER':([23,42,],[29,-9,]),'STRING':([25,30,35,50,],[31,36,41,54,]),'YOUTH':([28,47,],[34,-10,]),'INTERNATIONAL':([33,52,],[39,-11,]),'SEASON_NAME':([38,55,],[44,-12,]),'BOOLEAN':([40,45,],[46,51,]),'MATCH':([43,57,],[49,-13,]),'UPDATED':([56,],[60,]),'UPDATED_360':([59,75,76,],[63,-16,-17,]),'AVAILABLE_360':([62,80,81,],[66,-18,-19,]),'TIMESTAMP':([64,67,72,77,],[68,73,78,82,]),'NULL':([64,67,72,77,],[69,74,79,83,]),'AVAILABLE':([65,84,85,],[71,-20,-21,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'json':([0,],[1,]),'contenido':([2,],[3,]),'elementos':([7,],[8,]),'estructura':([9,],[11,]),'competition_id':([9,],[12,]),'season_id':([12,],[15,]),'country':([15,],[19,]),'competition_name':([19,],[23,]),'gender':([23,],[28,]),'youth':([28,],[33,]),'international':([33,],[38,]),'season_name':([38,],[43,]),'match':([43,],[48,]),'estructura_match':([56,],[58,]),'updated':([56,],[59,]),'updated360':([59,],[62,]),'available360':([62,],[65,]),'available':([65,],[70,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> json","S'",1,None,None,None),
  ('json -> LLAVE_ABRE contenido LLAVE_CIERRA','json',3,'p_json','assig_yacc.py',5),
  ('contenido -> ROOT DOSPUNTOS COR_ABRE elementos COR_CIERRA','contenido',5,'p_contenido','assig_yacc.py',9),
  ('elementos -> LLAVE_ABRE estructura LLAVE_CIERRA COMA','elementos',4,'p_elementos_varios','assig_yacc.py',13),
  ('elementos -> LLAVE_ABRE estructura LLAVE_CIERRA','elementos',3,'p_elemento_final','assig_yacc.py',17),
  ('estructura -> competition_id season_id country competition_name gender youth international season_name match','estructura',9,'p_estructura','assig_yacc.py',21),
  ('competition_id -> COMPETITION_ID DOSPUNTOS NUMBER COMA','competition_id',4,'p_competition_id','assig_yacc.py',25),
  ('season_id -> SEASON_ID DOSPUNTOS NUMBER COMA','season_id',4,'p_season_id','assig_yacc.py',29),
  ('country -> COUNTRY DOSPUNTOS STRING COMA','country',4,'p_country','assig_yacc.py',33),
  ('competition_name -> COMPETITION_NAME DOSPUNTOS STRING COMA','competition_name',4,'p_competition_name','assig_yacc.py',37),
  ('gender -> GENDER DOSPUNTOS STRING COMA','gender',4,'p_gender','assig_yacc.py',41),
  ('youth -> YOUTH DOSPUNTOS BOOLEAN COMA','youth',4,'p_youth','assig_yacc.py',45),
  ('international -> INTERNATIONAL DOSPUNTOS BOOLEAN COMA','international',4,'p_international','assig_yacc.py',49),
  ('season_name -> SEASON_NAME DOSPUNTOS STRING COMA','season_name',4,'p_season_name','assig_yacc.py',53),
  ('match -> MATCH DOSPUNTOS LLAVE_ABRE estructura_match LLAVE_CIERRA','match',5,'p_match','assig_yacc.py',57),
  ('estructura_match -> updated updated360 available360 available','estructura_match',4,'p_estructura_match','assig_yacc.py',61),
  ('updated -> UPDATED DOSPUNTOS TIMESTAMP COMA','updated',4,'p_updated','assig_yacc.py',65),
  ('updated -> UPDATED DOSPUNTOS NULL COMA','updated',4,'p_updated_null','assig_yacc.py',69),
  ('updated360 -> UPDATED_360 DOSPUNTOS TIMESTAMP COMA','updated360',4,'p_updated360','assig_yacc.py',73),
  ('updated360 -> UPDATED_360 DOSPUNTOS NULL COMA','updated360',4,'p_updated360_null','assig_yacc.py',77),
  ('available360 -> AVAILABLE_360 DOSPUNTOS TIMESTAMP COMA','available360',4,'p_available360','assig_yacc.py',81),
  ('available360 -> AVAILABLE_360 DOSPUNTOS NULL COMA','available360',4,'p_available360_null','assig_yacc.py',85),
  ('available -> AVAILABLE DOSPUNTOS TIMESTAMP','available',3,'p_available','assig_yacc.py',89),
  ('available -> AVAILABLE DOSPUNTOS NULL','available',3,'p_available_null','assig_yacc.py',93),
]
