
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AVAILABLE AVAILABLE_360 BOOLEAN COMA COMPETITION_ID COMPETITION_NAME COR_ABRE COR_CIERRA COUNTRY DOSPUNTOS GENDER INTERNATIONAL LLAVE_ABRE LLAVE_CIERRA MATCH NULL NUMBER ROOT SEASON_ID SEASON_NAME STRING TIMESTAMP UPDATED UPDATED_360 YOUTHjson : LLAVE_ABRE contenido LLAVE_CIERRAcontenido : ROOT DOSPUNTOS COR_ABRE elementos COR_CIERRAelementos : elementos COMA elementoelementos : elementoelemento : LLAVE_ABRE estructura LLAVE_CIERRAestructura : competition_id season_id country competition_name gender youth international season_name matchcompetition_id : COMPETITION_ID DOSPUNTOS NUMBER COMAseason_id : SEASON_ID DOSPUNTOS NUMBER COMAcountry : COUNTRY DOSPUNTOS STRING COMAcompetition_name : COMPETITION_NAME DOSPUNTOS STRING COMAgender : GENDER DOSPUNTOS STRING COMAyouth : YOUTH DOSPUNTOS BOOLEAN COMAinternational : INTERNATIONAL DOSPUNTOS BOOLEAN COMAseason_name : SEASON_NAME DOSPUNTOS STRING COMAmatch : MATCH DOSPUNTOS LLAVE_ABRE estructura_match LLAVE_CIERRAestructura_match : updated updated360 available360 availableupdated : UPDATED DOSPUNTOS TIMESTAMP COMAupdated : UPDATED DOSPUNTOS NULL COMAupdated360 : UPDATED_360 DOSPUNTOS TIMESTAMP COMAupdated360 : UPDATED_360 DOSPUNTOS NULL COMAavailable360 : AVAILABLE_360 DOSPUNTOS TIMESTAMP COMAavailable360 : AVAILABLE_360 DOSPUNTOS NULL COMAavailable : AVAILABLE DOSPUNTOS TIMESTAMPavailable : AVAILABLE DOSPUNTOS NULL'
    
_lr_action_items = {'LLAVE_ABRE':([0,7,12,55,],[2,10,10,58,]),'$end':([1,5,],[0,-1,]),'ROOT':([2,],[4,]),'LLAVE_CIERRA':([3,11,13,50,60,63,72,84,85,],[5,-2,17,-6,63,-15,-16,-23,-24,]),'DOSPUNTOS':([4,15,19,22,26,31,36,41,46,51,62,65,68,73,],[6,20,23,27,32,37,42,47,52,55,66,69,74,79,]),'COR_ABRE':([6,],[7,]),'COR_CIERRA':([8,9,16,17,],[11,-4,-3,-5,]),'COMA':([8,9,16,17,24,28,33,38,43,48,53,56,70,71,75,76,80,81,],[12,-4,-3,-5,29,34,39,44,49,54,57,59,77,78,82,83,86,87,]),'COMPETITION_ID':([10,],[15,]),'SEASON_ID':([14,29,],[19,-7,]),'COUNTRY':([18,34,],[22,-8,]),'NUMBER':([20,23,],[24,28,]),'COMPETITION_NAME':([21,39,],[26,-9,]),'GENDER':([25,44,],[31,-10,]),'STRING':([27,32,37,52,],[33,38,43,56,]),'YOUTH':([30,49,],[36,-11,]),'INTERNATIONAL':([35,54,],[41,-12,]),'SEASON_NAME':([40,57,],[46,-13,]),'BOOLEAN':([42,47,],[48,53,]),'MATCH':([45,59,],[51,-14,]),'UPDATED':([58,],[62,]),'UPDATED_360':([61,77,78,],[65,-17,-18,]),'AVAILABLE_360':([64,82,83,],[68,-19,-20,]),'TIMESTAMP':([66,69,74,79,],[70,75,80,84,]),'NULL':([66,69,74,79,],[71,76,81,85,]),'AVAILABLE':([67,86,87,],[73,-21,-22,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'json':([0,],[1,]),'contenido':([2,],[3,]),'elementos':([7,],[8,]),'elemento':([7,12,],[9,16,]),'estructura':([10,],[13,]),'competition_id':([10,],[14,]),'season_id':([14,],[18,]),'country':([18,],[21,]),'competition_name':([21,],[25,]),'gender':([25,],[30,]),'youth':([30,],[35,]),'international':([35,],[40,]),'season_name':([40,],[45,]),'match':([45,],[50,]),'estructura_match':([58,],[60,]),'updated':([58,],[61,]),'updated360':([61,],[64,]),'available360':([64,],[67,]),'available':([67,],[72,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> json","S'",1,None,None,None),
  ('json -> LLAVE_ABRE contenido LLAVE_CIERRA','json',3,'p_json','assig_yacc.py',5),
  ('contenido -> ROOT DOSPUNTOS COR_ABRE elementos COR_CIERRA','contenido',5,'p_contenido','assig_yacc.py',10),
  ('elementos -> elementos COMA elemento','elementos',3,'p_elementos_multiple','assig_yacc.py',16),
  ('elementos -> elemento','elementos',1,'p_elementos_single','assig_yacc.py',22),
  ('elemento -> LLAVE_ABRE estructura LLAVE_CIERRA','elemento',3,'p_elemento','assig_yacc.py',27),
  ('estructura -> competition_id season_id country competition_name gender youth international season_name match','estructura',9,'p_estructura','assig_yacc.py',32),
  ('competition_id -> COMPETITION_ID DOSPUNTOS NUMBER COMA','competition_id',4,'p_competition_id','assig_yacc.py',37),
  ('season_id -> SEASON_ID DOSPUNTOS NUMBER COMA','season_id',4,'p_season_id','assig_yacc.py',42),
  ('country -> COUNTRY DOSPUNTOS STRING COMA','country',4,'p_country','assig_yacc.py',47),
  ('competition_name -> COMPETITION_NAME DOSPUNTOS STRING COMA','competition_name',4,'p_competition_name','assig_yacc.py',52),
  ('gender -> GENDER DOSPUNTOS STRING COMA','gender',4,'p_gender','assig_yacc.py',57),
  ('youth -> YOUTH DOSPUNTOS BOOLEAN COMA','youth',4,'p_youth','assig_yacc.py',62),
  ('international -> INTERNATIONAL DOSPUNTOS BOOLEAN COMA','international',4,'p_international','assig_yacc.py',67),
  ('season_name -> SEASON_NAME DOSPUNTOS STRING COMA','season_name',4,'p_season_name','assig_yacc.py',72),
  ('match -> MATCH DOSPUNTOS LLAVE_ABRE estructura_match LLAVE_CIERRA','match',5,'p_match','assig_yacc.py',82),
  ('estructura_match -> updated updated360 available360 available','estructura_match',4,'p_estructura_match','assig_yacc.py',87),
  ('updated -> UPDATED DOSPUNTOS TIMESTAMP COMA','updated',4,'p_updated','assig_yacc.py',93),
  ('updated -> UPDATED DOSPUNTOS NULL COMA','updated',4,'p_updated_null','assig_yacc.py',98),
  ('updated360 -> UPDATED_360 DOSPUNTOS TIMESTAMP COMA','updated360',4,'p_updated360','assig_yacc.py',103),
  ('updated360 -> UPDATED_360 DOSPUNTOS NULL COMA','updated360',4,'p_updated360_null','assig_yacc.py',108),
  ('available360 -> AVAILABLE_360 DOSPUNTOS TIMESTAMP COMA','available360',4,'p_available360','assig_yacc.py',113),
  ('available360 -> AVAILABLE_360 DOSPUNTOS NULL COMA','available360',4,'p_available360_null','assig_yacc.py',118),
  ('available -> AVAILABLE DOSPUNTOS TIMESTAMP','available',3,'p_available','assig_yacc.py',123),
  ('available -> AVAILABLE DOSPUNTOS NULL','available',3,'p_available_null','assig_yacc.py',128),
]
